
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  font_awesome_flutter: ^8.5.0
  curved_navigation_bar: ^0.3.1
  flutter_icons: ^1.0.0+1
  
  assets:
      - assets/images/1.jpg
      - assets/images/1a.jpg
      - assets/images/1b.jpg
      - assets/images/o1.jpg
      - assets/images/o2.jpg
      - assets/images/o3.jpg
